<a href="https://colab.research.google.com/github/Nil1205/statistic/blob/main/Statistics_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [2]:
import numpy as np
import pandas as pd
from scipy import stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [3]:
samples = np.random.normal(100,15,1000)
samples

array([106.07831492, 123.02111637,  69.16371634, 102.42097761,
       108.90914923, 111.64214111, 114.04485469,  73.95411864,
        85.71396724, 131.10171801, 113.65507284,  85.30801529,
       133.92133389, 134.93312929,  98.64490049, 119.46766633,
        90.52468146,  98.52937627,  83.7241481 , 128.16251935,
        90.5294224 ,  97.94242285,  84.70978825,  84.8373157 ,
        95.65305079,  80.42432323, 136.81378818,  87.01098778,
        98.26880797, 117.42806413, 105.62821742, 108.93616696,
        90.88246638, 121.53243331,  96.20546675,  99.29407473,
        86.4271618 , 105.86928486,  94.11287932,  99.44637195,
       115.48427178, 121.28070018,  77.78573185, 104.64083376,
        96.33828541, 119.02813073, 117.80522119,  77.70268244,
       111.39815129, 133.16249106,  86.59875618,  66.29782138,
        95.60597327, 109.63965656,  93.98239208,  86.98879964,
        63.3325423 , 102.48505335,  83.41005163,  92.86370689,
        72.60142775,  87.74689502, 118.35664034, 120.44239662,
        92.9087437 ,  81.69356791,  89.07932056, 107.01373095,
       111.18028781, 106.12244471, 106.82620938,  91.74866978,
       104.14291432, 114.89812554, 104.98934444, 101.6280611 ,
       108.89152923, 117.06657963, 113.22436808, 104.76595875,
        98.1884698 , 115.13554267, 104.03241901,  96.83771165,
       107.56426184,  92.36530301, 120.79414922,  80.94237999,
       112.04974986, 114.62573567, 124.19631119, 112.08118386,
        78.62428144, 104.15579721, 110.68750545,  96.90742728,
        96.08775292, 103.55975419,  86.90148348, 123.34046353,
        98.65151051,  75.63538223,  78.20555509, 124.62181346,
       119.17646645, 108.74281595, 105.71767739,  99.23558997,
        98.58926649,  85.67960846,  69.02299126,  73.31536879,
       102.50941253, 103.8962447 ,  87.16018908,  97.36624231,
       102.19467375, 110.9882815 , 102.76076749,  70.15361868,
        90.07538362,  91.6758682 ,  88.81458416,  86.15550375,
       105.94277487, 106.83083198,  96.1856794 , 102.64480211,
       126.66656726, 130.43486813,  97.70658536,  97.00619482,
       102.47172893, 102.42226737, 119.64313517, 120.02959495,
        83.08693241,  92.71544515,  88.45868348,  95.8494508 ,
        81.57918721, 101.32520868,  91.97086133,  91.7232588 ,
        92.04327449,  88.41313593,  85.3940664 , 102.67316465,
        97.75719241,  97.54875439,  86.85006325,  95.99526902,
        80.93164953, 114.55840907,  81.64916939,  98.44711623,
        96.71799059, 113.38124408,  94.46857423, 126.42130313,
       108.65088853,  94.85403276,  99.94472155, 108.2011128 ,
       100.33839607, 112.86524457,  94.1179596 ,  93.67032176,
        99.60173031,  90.4194416 , 117.07194169, 116.24576884,
        85.69292697,  91.58128041,  97.76638081, 111.35196508,
       130.40416216,  97.30344418,  94.35499265,  77.02763015,
        75.39057681,  77.43933966, 104.99506087,  94.26623833,
       107.07428785, 103.85557545, 124.26926275, 107.84480881,
        98.89712734,  98.73820247,  95.52033864,  84.75804443,
       108.31851681,  86.22870846,  98.3437355 , 102.36406941,
       117.43937637, 106.30672244, 116.89565357,  95.70380127,
        92.40186861, 130.78833945, 101.17498888, 104.65434644,
       124.41224442,  83.59902043, 101.91486996,  83.14559819,
       135.47197323, 103.62679601, 108.4341298 , 108.11360898,
        82.64140041,  83.80004555,  81.43050712,  97.82577642,
       113.51703563, 100.58889114,  91.04092369,  94.21136961,
        95.9052176 , 113.26783653, 127.13433121,  97.37340604,
       109.70156006,  96.21629062,  85.11452623,  98.1983258 ,
        75.3233331 , 122.23796802, 101.11073965, 115.40107815,
        82.29773466, 101.47294106,  80.92283824,  69.15781159,
        57.01354744, 119.94994326,  98.02509881,  83.41878096,
       124.21197978,  95.73734923, 113.24676195, 112.63314118,
       105.52993464,  76.85640053, 116.89783344, 100.57391155,
       123.04039967,  95.81991821,  87.36916273, 116.25069983,
        96.91776458, 102.05332309,  97.22790173, 100.49089607,
       116.7012522 ,  96.66325644,  84.83411853, 100.85203164,
        93.29240534,  75.41673363,  93.84638284,  99.78077548,
       105.68484261,  82.69992182, 116.09369018,  93.10847459,
        90.91887888,  96.53532844, 107.35327358,  86.40766353,
       113.39350984, 107.12866949,  88.54279257,  89.61191422,
        92.89132365, 101.19493177,  91.81079322,  77.92177857,
       107.15400622,  99.00489767,  71.47037685, 126.53633151,
       121.02409807,  94.09490933,  79.43213434, 107.09410924,
        88.63448822,  88.68826033, 116.60551666,  91.24477103,
        98.93738819, 121.63713689, 104.97601047,  97.76175245,
       104.58695709, 109.90978815, 131.57605523, 100.8207349 ,
        96.28917923, 104.39460613, 106.49517594,  82.88968926,
       115.43695408, 111.31509365,  94.52560752, 115.85671775,
        83.30372013, 110.04551786, 118.46727172,  88.14886863,
        96.90832229,  94.06183482,  88.73482748,  98.77092849,
        98.57096133, 102.9119687 ,  85.41769839, 122.18868517,
       102.16784808, 103.2523092 , 119.85934019,  82.41418476,
        94.11816068,  90.88931471,  84.98547473,  97.89883075,
       101.13170597, 129.61988393,  83.14147833, 109.09261115,
        93.192456  , 110.09859225,  98.3592838 ,  99.80726407,
        82.60812167,  78.56599249,  97.79434097, 131.86167424,
       105.09569374, 106.20955763,  73.7328366 ,  93.84323933,
        95.32797635,  89.17831108, 132.50481316, 109.13156445,
       115.33959371, 102.7204287 ,  80.69111525, 123.84099334,
       101.71747652,  98.14192243,  96.12725461, 124.46097673,
        94.16355498, 107.18817428,  99.60866307,  89.18792181,
        97.8399614 , 109.90936189,  91.99926925, 124.02293542,
        89.29179987,  65.50225564, 108.33021843, 109.05080727,
        85.75891759,  87.88503312, 117.28871849, 102.05113015,
       102.80877136, 100.83166337, 144.45957721, 129.83976849,
       111.58904577,  84.10159977, 104.19950803, 101.10521906,
       111.56354963,  90.49715751, 100.29547388,  68.15947975,
       103.49393269, 105.69239724,  88.21289335, 120.21977425,
       105.28872547,  98.02289982,  87.47307449,  82.98660206,
       109.55133299, 114.81686653,  99.19520014, 118.92621931,
        99.83956266,  94.07576864,  94.81395788, 114.43467055,
        93.64819657,  89.54940396,  93.41923689,  83.68805016,
        95.08355782,  91.3213557 ,  95.66316858,  86.0752438 ,
       115.52597758,  83.15308497,  99.27182482, 114.68991882,
        94.04674932, 117.99442935,  76.51968216, 129.96452945,
       113.93300515, 121.19615049, 111.91719862,  82.761291  ,
        96.50154263, 113.14974252,  88.59367686, 120.72288817,
        88.66922476,  79.06713304,  86.43711242, 102.79102781,
       108.13378178, 123.96616991,  98.2481085 ,  92.71500589,
       103.32371355,  98.38633694,  65.9270564 , 115.56137677,
       106.33009675,  97.75388044,  69.10941647,  93.70657926,
       121.45280563,  97.39927843, 114.72953808,  86.99699343,
       120.31540742, 121.86508898, 114.16928246,  90.51527645,
        90.91531999,  87.59855265, 133.98640122,  89.32796289,
       100.87786723,  96.78017967,  81.85103299, 109.01876684,
       109.7050744 , 112.40221181,  76.49854438,  93.3738971 ,
       112.66503943,  97.36822327, 101.31298659,  97.42540385,
        90.85202075,  88.13352931,  98.95220441, 109.18402255,
        77.57532551, 105.70232262,  59.63483051, 103.17353753,
        84.08821422, 104.72197864,  84.0377475 ,  93.93320107,
       125.93977944, 107.86455513,  96.41378362, 108.39834595,
        89.57114706, 111.64052487, 100.099788  ,  72.49283095,
       117.27836696, 108.20455368, 107.24092046,  85.44599197,
        81.58282928, 112.63772087,  88.5324929 ,  99.89511117,
        83.85601832, 115.52038792,  91.38361407, 112.97023573,
        79.88010195, 107.26836473, 120.9211071 , 106.53643832,
        81.36334639,  89.15092838, 116.56280263,  98.08830228,
       104.15487587,  98.68151512,  98.94928379, 122.19430099,
        99.99085999,  89.7671835 , 130.19683722,  96.56833302,
        94.70439711, 114.54766872,  68.75436743, 107.11204578,
        93.43544965,  78.1178502 ,  82.4321376 , 100.83347768,
        85.08112843, 123.00700404, 120.30878161,  95.46680837,
        94.26704697, 100.02173965, 107.44707   , 101.37919692,
        89.81581843, 107.89676196,  98.80044753,  91.633603  ,
       100.32538211,  69.33205301, 114.61439972, 109.71639555,
       117.56231497, 115.73702575, 129.70840803,  97.54258787,
       124.80314202, 101.26471842,  94.58100584, 106.91164053,
       104.0068544 ,  84.77832726,  87.08810685,  72.84199281,
       112.22609172, 105.99018445, 121.74239781,  87.06595164,
       115.46918534, 107.02805113,  84.79937118, 103.65755299,
        92.00695388, 114.15294044, 110.85946602,  82.99639453,
        93.75625185,  85.93871482, 106.77512888, 118.56217241,
       101.91669367, 115.91643633,  87.01824873,  97.11964661,
       105.09160162,  72.45025198,  98.55946387, 101.36477825,
       103.6196547 ,  72.6150557 , 112.23804508, 107.3942456 ,
       117.91632856, 110.73265218, 110.29810187, 101.29721716,
        86.1070364 , 100.46171667,  81.56449601, 111.15219126,
        88.22864334,  78.39097334, 114.68267473,  98.51917294,
       105.94440509, 103.29498398, 102.68540271,  99.98000331,
        92.01160218,  72.43087048, 126.7657428 ,  97.47133163,
        96.32893271,  92.25689116,  92.39816595, 107.51358038,
        82.82813061,  96.1259547 ,  95.18782119,  93.52481965,
       101.06391524, 108.70355182, 105.3412391 ,  95.08037137,
       103.06542936, 140.0020828 , 120.93049807,  87.78119283,
       114.79144453,  81.75838456,  91.98489791, 104.3794573 ,
       110.07689616, 105.90512378,  76.05046786,  91.63408821,
        94.40908815,  90.4315224 , 115.42805738, 126.22474725,
       105.58839125, 110.75279619,  88.85610546,  72.426588  ,
        80.64405425,  79.56349213, 132.03399469,  78.32149683,
        79.92329616,  80.36510352,  78.68982715,  83.37030606,
        99.25211896,  81.35347255,  93.04989903,  99.16409473,
        92.0098265 ,  61.31394643, 106.71068891, 120.87064972,
        95.94688753, 127.20434306,  87.90395788, 107.77074442,
        92.50585376,  95.87474175,  81.7831567 , 108.22657387,
       109.60664288,  94.96822744,  99.76753633, 116.68967994,
        94.16578174,  83.64990473, 103.51281441, 100.50307128,
       102.3624001 ,  88.8993005 ,  91.95779465,  79.47265112,
       110.34284569, 103.26887395,  81.21447251,  99.49292976,
       106.79684475, 109.51661831, 116.19428367,  98.27458056,
        84.68090399,  95.99560371,  78.5536001 ,  91.0931061 ,
       104.74881908, 101.30046174, 125.43906499,  93.79583655,
        95.73673712, 124.79665371,  86.27855556, 100.87136471,
        81.13203386,  97.47503335, 130.12398242, 104.96033823,
        98.82258733,  78.86589581,  94.267995  ,  97.16261683,
        71.73011902,  96.61470361, 111.60971631,  96.51818957,
       107.43216717,  83.74003987,  84.90478203, 110.38503491,
        98.10709116, 100.78968868, 112.24641707, 108.13756766,
        83.16920132,  79.0343152 ,  95.72722235, 101.48580982,
        94.54223279,  85.45568274,  89.57346964, 108.27426797,
        76.10854839, 108.95768689,  96.99937512, 109.14588488,
        72.91886715,  78.56226512,  68.71705248, 101.64408419,
        84.5547232 , 119.67161114, 103.8496767 , 127.72679695,
       107.93094145, 116.84915795, 110.14803469,  92.14748153,
        68.89252826, 125.59098768,  95.49883918,  98.40261209,
       124.64389778, 117.86802969,  92.73649799, 137.15089563,
        95.03212224, 114.77925106,  97.21492869,  94.71416419,
       104.11394949,  87.74662405, 105.03694944,  88.01232636,
        88.39672606, 121.71616959,  68.95492125, 123.11397783,
        87.26416436,  85.38139201,  92.69229243,  91.12356888,
        80.03931371, 107.57213589,  93.05863933,  76.54179475,
        78.3104835 , 106.85034349, 111.31934352, 125.98649521,
        76.39983499, 109.57623187,  91.33086851,  88.58647992,
       106.63341166,  84.48398668,  97.64762635,  84.21648119,
       140.90665092, 115.22549943,  75.82262176, 115.71614857,
       105.56279674, 108.38705795, 115.64025734,  74.87724286,
       102.73958241,  91.47498978,  81.67786195,  91.78206565,
       105.60118992,  87.6041209 ,  97.95229848, 107.54576743,
       114.65822485, 116.82577163,  95.26551783,  97.78720683,
       117.25719334,  91.32485073, 101.62450996, 103.54846548,
        97.36226214, 115.7965868 , 111.16418082,  93.36728143,
        98.48248532,  93.93029003, 121.76194887, 106.28979579,
       104.35574727,  81.92487605,  91.97065109,  84.32402694,
       117.50370015, 103.0427466 , 119.30002836, 101.55358625,
       111.25866119, 102.99094119, 103.71414937, 102.65062829,
       104.18661065,  90.08698757,  99.127888  ,  91.22029817,
       124.25647318, 116.52664402,  92.35731965, 110.7920572 ,
        85.95470796,  98.02271268, 100.0392068 , 111.63712662,
        94.39727702,  99.18019706,  81.78040772, 114.1601188 ,
       124.48884841, 105.4918524 ,  79.58947014,  70.58917351,
        96.1110767 , 113.7859779 ,  98.72353768, 105.34365042,
       117.09789153, 115.84844433,  80.90216743,  93.11630214,
        86.65463167,  99.19959518,  85.79305019, 112.08768028,
        82.9337598 ,  96.56272806,  86.76413391,  97.58494   ,
       122.82800122, 108.03361591, 119.79288855,  89.10385582,
        98.202615  ,  94.71008737, 108.90362446,  88.19209826,
       108.64543978, 110.68266886,  87.11974442, 101.93519799,
        99.71725287,  73.38541176,  88.07304872,  90.73458145,
       101.73660919,  95.1550585 ,  81.7518995 ,  99.22202753,
       101.04058811, 102.57197821,  97.19824917, 134.16050175,
        93.51711697, 112.53996061, 121.75690972, 128.61847293,
        84.90355339,  90.8329418 , 109.7819524 ,  92.64600824,
       109.7094538 ,  81.8598132 ,  98.030115  , 114.5217392 ,
       105.61407295,  86.4082067 , 111.93914732,  99.91884415,
       127.59893659, 117.55156812,  79.49686815,  97.65049787,
       100.8158495 , 117.46346733,  74.00393543,  88.67366039,
        92.57423091, 133.93357569, 105.93153654,  85.55463198,
        96.04760232, 102.28705965,  89.32243197, 107.93268902,
       155.12174196,  98.70137955, 109.72275447, 123.00849872,
       104.09939864, 109.08099645,  97.47161176, 106.56147138,
       124.26319169, 112.21173762,  90.51802423, 110.24906012,
       105.15095019, 132.48997041,  89.03884144,  98.11055603,
        62.23800071,  96.42938975,  75.9881502 , 106.69444018,
        91.97821307,  86.92376791, 105.49112361, 114.61026313,
       101.03518319, 105.82465383, 102.54398834, 113.45172673,
       116.91276042, 103.57120886,  95.15323639,  98.85596022,
       105.619826  ,  98.12237112,  97.02538074,  94.5501116 ,
        88.42031788, 110.74817547, 102.1724329 ,  98.64110799,
        88.71414158,  93.83176677,  97.16485799, 124.20971116,
       106.22449923, 102.70227253,  86.64240871, 108.45070503,
       113.30273934, 111.65126869,  78.61715002, 119.78178234,
       125.05112327, 101.19057029,  89.8146621 , 105.00693443,
       102.59868411, 103.3208874 ,  99.8776701 ,  85.90476101,
        66.19442096, 124.32760751, 151.26293795,  89.37687594,
        86.05450996, 126.22660074,  83.17380312,  74.36706004,
        92.68963956, 105.08300332, 121.28693979, 104.01111461,
       119.44329203,  74.89505675, 116.82000892, 108.0035155 ,
        93.14796142, 107.56311529, 106.84901933,  93.91503903,
        79.47367841,  87.62698734,  87.571584  , 106.56951383,
        96.02190679,  92.86538505,  90.21442784,  95.60638597,
        95.82596351,  77.21910706,  91.57229964,  91.2150687 ,
        80.97493741, 123.51897959, 109.37890524,  88.15289667])

Compute the **mean**, **median**, and **mode**

In [15]:
mean =round(np.mean(samples),3)
median =round(np.median(samples),3)
mode =stats.mode(samples)
print("mean is {}, median is {} and mode is {}.".format(mean, median, mode))

mean is 100.013, median is 99.066 and mode is ModeResult(mode=array([57.01354744]), count=array([1])).

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [18]:
min = round(np.min(samples),2)
max =round(np.max(samples),2)
q1 =round(np.percentile(samples, 25),2)
q3 =round(np.percentile(samples, 75),2)
iqr =round(stats.iqr(samples),2)
iqr2=round((q3-q1),2)
print("min= ", min)
print("max= ", max)
print("q1= ", q1)
print("q3= ", q3)
print("iqr: {} and iqr2: {} are equal.".format(iqr,iqr2))

min=  57.01
max=  155.12
q1=  89.82
q3=  109.53
iqr: 19.71 and iqr2: 19.71 are equal.

Compute the **variance** and **standard deviation**

In [22]:
variance = round(np.var(samples),3)
std_dev =round(np.std(samples),3)
print("variance= {}, std_dev= {} ".format(variance, std_dev))

variance= 215.371, std_dev= 14.676

Compute the **skewness** and **kurtosis**

In [23]:
skewness =round(stats.skew(samples),3)
kurtosis =round(stats.kurtosis(samples),3)
print("skewness= {}, kurtosis= {}".format(skewness, kurtosis))

skewness= 0.167, kurtosis= 0.032

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [24]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [26]:

y=np.array([13,6,7,34,47,23,56,34,5,1])
y

array([13,  6,  7, 34, 47, 23, 56, 34,  5,  1])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [27]:
r = np.corrcoef(x,y)
r

array([[1.        , 0.05889366],
       [0.05889366, 1.        ]])

## Pandas Correlation Calculation

Run the code below

In [28]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [31]:
r =stats.pearsonr(x,y)
r

(0.758640289091187, 0.010964341301680813)

In [32]:
r = x.corr(y)
r= y.corr(x)
r

0.7586402890911869

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [35]:
rho =x.corr(y, method='spearman')
rho

0.9757575757575757

## Seaborn Dataset Tips

Import Seaborn Library

In [36]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [37]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [38]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [41]:
tips.corr('pearson')

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000